# Generated by Django 2.0.13 on 2019-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
