# Generated by Django 2.0.13 on 2019-08-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cod_barras',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
