# Generated by Django 2.0.13 on 2019-08-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_produto_cod_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cnpj', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
