# Generated by Django 2.0.13 on 2019-08-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190819_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='estador',
            new_name='estado',
        ),
    ]
